//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemperatureMeasurementTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemperatureMeasurementTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ° ähnelt.
        /// </summary>
        public static string DegreeSymbol {
            get {
                return ResourceManager.GetString("DegreeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlermeldung ähnelt.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei wird gerade verwedent. Bitte schließen sie vorerst Excel. ähnelt.
        /// </summary>
        public static string ErrorMessageExcelFileIsStillOpen {
            get {
                return ResourceManager.GetString("ErrorMessageExcelFileIsStillOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel vorher schließen ähnelt.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_Date {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kürzel ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_FirstEmployee {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_FirstEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Temperatur ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_FirstTemp {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_FirstTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uhrzeit ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_FirstTime {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_FirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kürzel ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_SecondEmployee {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_SecondEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Temperatur ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_SecondTemp {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_SecondTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uhrzeit ähnelt.
        /// </summary>
        public static string ExcelFile_TitleColumn_SecondTime {
            get {
                return ResourceManager.GetString("ExcelFile_TitleColumn_SecondTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feiertag ähnelt.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Urlaub eintragen ähnelt.
        /// </summary>
        public static string MainWindow_EnterVacation {
            get {
                return ResourceManager.GetString("MainWindow_EnterVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TMT ähnelt.
        /// </summary>
        public static string MainWindow_Header_Title {
            get {
                return ResourceManager.GetString("MainWindow_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeitender Mitarbeiter ähnelt.
        /// </summary>
        public static string MainWindow_Label_AssignedUser {
            get {
                return ResourceManager.GetString("MainWindow_Label_AssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string MainWindow_Label_Date {
            get {
                return ResourceManager.GetString("MainWindow_Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fertig ähnelt.
        /// </summary>
        public static string MainWindow_Label_Done {
            get {
                return ResourceManager.GetString("MainWindow_Label_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperatureingabe ähnelt.
        /// </summary>
        public static string MainWindow_Label_Temperature {
            get {
                return ResourceManager.GetString("MainWindow_Label_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitangabe ähnelt.
        /// </summary>
        public static string MainWindow_Label_Time {
            get {
                return ResourceManager.GetString("MainWindow_Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string MainWindow_Label_VacationDescription {
            get {
                return ResourceManager.GetString("MainWindow_Label_VacationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Urlaub von ähnelt.
        /// </summary>
        public static string MainWindow_Label_VacationFrom {
            get {
                return ResourceManager.GetString("MainWindow_Label_VacationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Urlaub bis ähnelt.
        /// </summary>
        public static string MainWindow_Label_VacationTo {
            get {
                return ResourceManager.GetString("MainWindow_Label_VacationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eintrag erfolgreich abgespeichert ähnelt.
        /// </summary>
        public static string MainWindow_Message_SuccessfullyEntered {
            get {
                return ResourceManager.GetString("MainWindow_Message_SuccessfullyEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TMT Eingabe ähnelt.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperatur über dem Limit! ähnelt.
        /// </summary>
        public static string MainWindow_ToolTip_Temperature_Warning {
            get {
                return ResourceManager.GetString("MainWindow_ToolTip_Temperature_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhalt ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDFs erstellen ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_CreatePDFs {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_CreatePDFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitarbeiter ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_Employee {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Exceldatei bekannt. \n Wählen Sie eine Datei aus oder erstellen Sie eine Neue. ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_ErrorTextNoExcelFile {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_ErrorTextNoExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_File {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateispeicherort ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_FileLocation {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfänger ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_MailsReciever {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_MailsReciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sender ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_MailsSender {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_MailsSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_OpenDoc {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_OpenDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drucken ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_PrintDoc {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_PrintDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_Program {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_Save {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als E-Mail versenden ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_SendAsMail {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_SendAsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperatureingabe ähnelt.
        /// </summary>
        public static string SettingsDialog_Label_TemperatureInput {
            get {
                return ResourceManager.GetString("SettingsDialog_Label_TemperatureInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen gespeichert ähnelt.
        /// </summary>
        public static string SettingsDialog_Message_SuccessfullySaved {
            get {
                return ResourceManager.GetString("SettingsDialog_Message_SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach der Eingabe Programm schließen ähnelt.
        /// </summary>
        public static string SettingsDialog_Programm_CloseAfterSave {
            get {
                return ResourceManager.GetString("SettingsDialog_Programm_CloseAfterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;span style=&apos;font-size: 12pt; font-family:Calibri; color: black;&apos;&gt;Im Anhang befinden sich die Temperaturmessungen&lt;/span&gt; ähnelt.
        /// </summary>
        public static string SettingsDialog_SendingMail_Body {
            get {
                return ResourceManager.GetString("SettingsDialog_SendingMail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExportExcelFileMessage.eml ähnelt.
        /// </summary>
        public static string SettingsDialog_SendingMail_MessageName {
            get {
                return ResourceManager.GetString("SettingsDialog_SendingMail_MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperaturmessung Exceldatei Export ähnelt.
        /// </summary>
        public static string SettingsDialog_SendingMail_Subject {
            get {
                return ResourceManager.GetString("SettingsDialog_SendingMail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TMT Einstellungen ähnelt.
        /// </summary>
        public static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Datei auswählen ähnelt.
        /// </summary>
        public static string SettingsDialog_ToolTip_ChooseExcelFile {
            get {
                return ResourceManager.GetString("SettingsDialog_ToolTip_ChooseExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Datei erstellen ähnelt.
        /// </summary>
        public static string SettingsDialog_ToolTip_CreateExcelFile {
            get {
                return ResourceManager.GetString("SettingsDialog_ToolTip_CreateExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Urlaub ähnelt.
        /// </summary>
        public static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.1 ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wochenende ähnelt.
        /// </summary>
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
    }
}
